#!/usr/bin/with-contenv bash

adduser -D -u 2000 shellinabox
echo 'shellinabox:<removed>' | chpasswd
echo 'root:<removed>' | chpasswd


echo "
-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u shellinabox)
User gid:    $(id -g shellinabox)
-------------------------------------
"
